// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: protos/borrowers.proto

package borrowers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateBorrowerRequest message represents a create borrower request
type CreateBorrowerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId     string `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BorrowDate string `protobuf:"bytes,3,opt,name=borrow_date,json=borrowDate,proto3" json:"borrow_date,omitempty"`
	ReturnDate string `protobuf:"bytes,4,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
}

func (x *CreateBorrowerRequest) Reset() {
	*x = CreateBorrowerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBorrowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBorrowerRequest) ProtoMessage() {}

func (x *CreateBorrowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBorrowerRequest.ProtoReflect.Descriptor instead.
func (*CreateBorrowerRequest) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBorrowerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBorrowerRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *CreateBorrowerRequest) GetBorrowDate() string {
	if x != nil {
		return x.BorrowDate
	}
	return ""
}

func (x *CreateBorrowerRequest) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

// CreateBorrowerResponse message represents a create borrower response
type CreateBorrowerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Borrower *Borrower `protobuf:"bytes,1,opt,name=borrower,proto3" json:"borrower,omitempty"`
}

func (x *CreateBorrowerResponse) Reset() {
	*x = CreateBorrowerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBorrowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBorrowerResponse) ProtoMessage() {}

func (x *CreateBorrowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBorrowerResponse.ProtoReflect.Descriptor instead.
func (*CreateBorrowerResponse) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBorrowerResponse) GetBorrower() *Borrower {
	if x != nil {
		return x.Borrower
	}
	return nil
}

// GetBorrowerByIdRequest message represents a get borrower by ID request
type GetBorrowerByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBorrowerByIdRequest) Reset() {
	*x = GetBorrowerByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBorrowerByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBorrowerByIdRequest) ProtoMessage() {}

func (x *GetBorrowerByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBorrowerByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBorrowerByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{2}
}

func (x *GetBorrowerByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetBorrowerByIdResponse message represents a get borrower by ID response
type GetBorrowerByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Borrower *Borrower `protobuf:"bytes,1,opt,name=borrower,proto3" json:"borrower,omitempty"`
}

func (x *GetBorrowerByIdResponse) Reset() {
	*x = GetBorrowerByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBorrowerByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBorrowerByIdResponse) ProtoMessage() {}

func (x *GetBorrowerByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBorrowerByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBorrowerByIdResponse) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{3}
}

func (x *GetBorrowerByIdResponse) GetBorrower() *Borrower {
	if x != nil {
		return x.Borrower
	}
	return nil
}

// UpdateBorrowerRequest message represents an update borrower request
type UpdateBorrowerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId     string `protobuf:"bytes,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BorrowDate string `protobuf:"bytes,4,opt,name=borrow_date,json=borrowDate,proto3" json:"borrow_date,omitempty"`
	ReturnDate string `protobuf:"bytes,5,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
}

func (x *UpdateBorrowerRequest) Reset() {
	*x = UpdateBorrowerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBorrowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBorrowerRequest) ProtoMessage() {}

func (x *UpdateBorrowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBorrowerRequest.ProtoReflect.Descriptor instead.
func (*UpdateBorrowerRequest) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBorrowerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBorrowerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateBorrowerRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *UpdateBorrowerRequest) GetBorrowDate() string {
	if x != nil {
		return x.BorrowDate
	}
	return ""
}

func (x *UpdateBorrowerRequest) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

// UpdateBorrowerResponse message represents an update borrower response
type UpdateBorrowerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Borrower *Borrower `protobuf:"bytes,1,opt,name=borrower,proto3" json:"borrower,omitempty"`
}

func (x *UpdateBorrowerResponse) Reset() {
	*x = UpdateBorrowerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBorrowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBorrowerResponse) ProtoMessage() {}

func (x *UpdateBorrowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBorrowerResponse.ProtoReflect.Descriptor instead.
func (*UpdateBorrowerResponse) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBorrowerResponse) GetBorrower() *Borrower {
	if x != nil {
		return x.Borrower
	}
	return nil
}

// DeleteBorrowerRequest message represents a delete borrower request
type DeleteBorrowerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBorrowerRequest) Reset() {
	*x = DeleteBorrowerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBorrowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBorrowerRequest) ProtoMessage() {}

func (x *DeleteBorrowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBorrowerRequest.ProtoReflect.Descriptor instead.
func (*DeleteBorrowerRequest) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBorrowerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteBorrowerResponse message represents a delete borrower response
type DeleteBorrowerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteBorrowerResponse) Reset() {
	*x = DeleteBorrowerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBorrowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBorrowerResponse) ProtoMessage() {}

func (x *DeleteBorrowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBorrowerResponse.ProtoReflect.Descriptor instead.
func (*DeleteBorrowerResponse) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBorrowerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetAllBorrowersRequest message represents a get all borrowers request
type GetAllBorrowersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId     string `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BorrowDate string `protobuf:"bytes,3,opt,name=borrow_date,json=borrowDate,proto3" json:"borrow_date,omitempty"`
	ReturnDate string `protobuf:"bytes,4,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
}

func (x *GetAllBorrowersRequest) Reset() {
	*x = GetAllBorrowersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBorrowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBorrowersRequest) ProtoMessage() {}

func (x *GetAllBorrowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBorrowersRequest.ProtoReflect.Descriptor instead.
func (*GetAllBorrowersRequest) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllBorrowersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAllBorrowersRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *GetAllBorrowersRequest) GetBorrowDate() string {
	if x != nil {
		return x.BorrowDate
	}
	return ""
}

func (x *GetAllBorrowersRequest) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

// Borrower message represents a borrower entity
type Borrower struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId     string `protobuf:"bytes,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BorrowDate string `protobuf:"bytes,4,opt,name=borrow_date,json=borrowDate,proto3" json:"borrow_date,omitempty"`
	ReturnDate string `protobuf:"bytes,5,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	CreatedAt  string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  string `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Borrower) Reset() {
	*x = Borrower{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Borrower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Borrower) ProtoMessage() {}

func (x *Borrower) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Borrower.ProtoReflect.Descriptor instead.
func (*Borrower) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{9}
}

func (x *Borrower) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Borrower) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Borrower) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Borrower) GetBorrowDate() string {
	if x != nil {
		return x.BorrowDate
	}
	return ""
}

func (x *Borrower) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *Borrower) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Borrower) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// GetAllBorrowersResponse message represents a get all borrowers response
type GetAllBorrowersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Borrowers []*Borrower `protobuf:"bytes,1,rep,name=borrowers,proto3" json:"borrowers,omitempty"`
}

func (x *GetAllBorrowersResponse) Reset() {
	*x = GetAllBorrowersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBorrowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBorrowersResponse) ProtoMessage() {}

func (x *GetAllBorrowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBorrowersResponse.ProtoReflect.Descriptor instead.
func (*GetAllBorrowersResponse) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllBorrowersResponse) GetBorrowers() []*Borrower {
	if x != nil {
		return x.Borrowers
	}
	return nil
}

// GetBorrowingHistoryRequest message represents a get borrowing history request
type GetBorrowingHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetBorrowingHistoryRequest) Reset() {
	*x = GetBorrowingHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBorrowingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBorrowingHistoryRequest) ProtoMessage() {}

func (x *GetBorrowingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBorrowingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetBorrowingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{11}
}

func (x *GetBorrowingHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetBorrowingHistoryResponse message represents a get borrowing history response
type GetBorrowingHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentlyBorrowed []*Borrower `protobuf:"bytes,1,rep,name=currently_borrowed,json=currentlyBorrowed,proto3" json:"currently_borrowed,omitempty"` // Books currently borrowed by the user
	History           []*Borrower `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`                                              // Historical records of borrowed books
}

func (x *GetBorrowingHistoryResponse) Reset() {
	*x = GetBorrowingHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBorrowingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBorrowingHistoryResponse) ProtoMessage() {}

func (x *GetBorrowingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBorrowingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetBorrowingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{12}
}

func (x *GetBorrowingHistoryResponse) GetCurrentlyBorrowed() []*Borrower {
	if x != nil {
		return x.CurrentlyBorrowed
	}
	return nil
}

func (x *GetBorrowingHistoryResponse) GetHistory() []*Borrower {
	if x != nil {
		return x.History
	}
	return nil
}

// GetBorrowedBooksByUserRequest message represents a get borrowed books by user request
type GetBorrowedBooksByUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetBorrowedBooksByUserRequest) Reset() {
	*x = GetBorrowedBooksByUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBorrowedBooksByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBorrowedBooksByUserRequest) ProtoMessage() {}

func (x *GetBorrowedBooksByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBorrowedBooksByUserRequest.ProtoReflect.Descriptor instead.
func (*GetBorrowedBooksByUserRequest) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{13}
}

func (x *GetBorrowedBooksByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BorrowedBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	AuthorId  string `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	GenreId   string `protobuf:"bytes,3,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	Summary   string `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAt string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *BorrowedBook) Reset() {
	*x = BorrowedBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowedBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowedBook) ProtoMessage() {}

func (x *BorrowedBook) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowedBook.ProtoReflect.Descriptor instead.
func (*BorrowedBook) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{14}
}

func (x *BorrowedBook) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BorrowedBook) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *BorrowedBook) GetGenreId() string {
	if x != nil {
		return x.GenreId
	}
	return ""
}

func (x *BorrowedBook) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *BorrowedBook) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BorrowedBook) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// GetBorrowedBooksByUserResponse message represents a get borrowed books by user response
type GetBorrowedBooksByUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books []*BorrowedBook `protobuf:"bytes,1,rep,name=Books,proto3" json:"Books,omitempty"`
}

func (x *GetBorrowedBooksByUserResponse) Reset() {
	*x = GetBorrowedBooksByUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrowers_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBorrowedBooksByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBorrowedBooksByUserResponse) ProtoMessage() {}

func (x *GetBorrowedBooksByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrowers_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBorrowedBooksByUserResponse.ProtoReflect.Descriptor instead.
func (*GetBorrowedBooksByUserResponse) Descriptor() ([]byte, []int) {
	return file_protos_borrowers_proto_rawDescGZIP(), []int{15}
}

func (x *GetBorrowedBooksByUserResponse) GetBooks() []*BorrowedBook {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_protos_borrowers_proto protoreflect.FileDescriptor

var file_protos_borrowers_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x61, 0x74,
	0x65, 0x22, 0x49, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x62,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x65, 0x72, 0x52, 0x08, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x08, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e,
	0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x08, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x65, 0x72, 0x22, 0x9b, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x65,
	0x22, 0x49, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x62, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65,
	0x72, 0x52, 0x08, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x15, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62,
	0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6f, 0x72, 0x72,
	0x6f, 0x77, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x22, 0xcc, 0x01, 0x0a, 0x08, 0x42, 0x6f, 0x72, 0x72,
	0x6f, 0x77, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x4c, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x31, 0x0a, 0x09, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73,
	0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x09, 0x62, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x65, 0x72, 0x73, 0x22, 0x35, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x69, 0x6e, 0x67, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x12, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x6c, 0x79, 0x5f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x11, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x6c, 0x79, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x12,
	0x2d, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x38,
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb4, 0x01, 0x0a, 0x0c, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x65, 0x6e, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x67, 0x65, 0x6e, 0x72, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x4f, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73,
	0x32, 0xa0, 0x05, 0x0a, 0x10, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x6f, 0x72, 0x72,
	0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72,
	0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x12,
	0x21, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x65, 0x72, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a,
	0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x12,
	0x20, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x12, 0x21, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x62, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x25, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x62,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72,
	0x6f, 0x77, 0x69, 0x6e, 0x67, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6d, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x28,
	0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x64,
	0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_borrowers_proto_rawDescOnce sync.Once
	file_protos_borrowers_proto_rawDescData = file_protos_borrowers_proto_rawDesc
)

func file_protos_borrowers_proto_rawDescGZIP() []byte {
	file_protos_borrowers_proto_rawDescOnce.Do(func() {
		file_protos_borrowers_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_borrowers_proto_rawDescData)
	})
	return file_protos_borrowers_proto_rawDescData
}

var file_protos_borrowers_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_protos_borrowers_proto_goTypes = []any{
	(*CreateBorrowerRequest)(nil),          // 0: borrowers.CreateBorrowerRequest
	(*CreateBorrowerResponse)(nil),         // 1: borrowers.CreateBorrowerResponse
	(*GetBorrowerByIdRequest)(nil),         // 2: borrowers.GetBorrowerByIdRequest
	(*GetBorrowerByIdResponse)(nil),        // 3: borrowers.GetBorrowerByIdResponse
	(*UpdateBorrowerRequest)(nil),          // 4: borrowers.UpdateBorrowerRequest
	(*UpdateBorrowerResponse)(nil),         // 5: borrowers.UpdateBorrowerResponse
	(*DeleteBorrowerRequest)(nil),          // 6: borrowers.DeleteBorrowerRequest
	(*DeleteBorrowerResponse)(nil),         // 7: borrowers.DeleteBorrowerResponse
	(*GetAllBorrowersRequest)(nil),         // 8: borrowers.GetAllBorrowersRequest
	(*Borrower)(nil),                       // 9: borrowers.Borrower
	(*GetAllBorrowersResponse)(nil),        // 10: borrowers.GetAllBorrowersResponse
	(*GetBorrowingHistoryRequest)(nil),     // 11: borrowers.GetBorrowingHistoryRequest
	(*GetBorrowingHistoryResponse)(nil),    // 12: borrowers.GetBorrowingHistoryResponse
	(*GetBorrowedBooksByUserRequest)(nil),  // 13: borrowers.GetBorrowedBooksByUserRequest
	(*BorrowedBook)(nil),                   // 14: borrowers.BorrowedBook
	(*GetBorrowedBooksByUserResponse)(nil), // 15: borrowers.GetBorrowedBooksByUserResponse
}
var file_protos_borrowers_proto_depIdxs = []int32{
	9,  // 0: borrowers.CreateBorrowerResponse.borrower:type_name -> borrowers.Borrower
	9,  // 1: borrowers.GetBorrowerByIdResponse.borrower:type_name -> borrowers.Borrower
	9,  // 2: borrowers.UpdateBorrowerResponse.borrower:type_name -> borrowers.Borrower
	9,  // 3: borrowers.GetAllBorrowersResponse.borrowers:type_name -> borrowers.Borrower
	9,  // 4: borrowers.GetBorrowingHistoryResponse.currently_borrowed:type_name -> borrowers.Borrower
	9,  // 5: borrowers.GetBorrowingHistoryResponse.history:type_name -> borrowers.Borrower
	14, // 6: borrowers.GetBorrowedBooksByUserResponse.Books:type_name -> borrowers.BorrowedBook
	0,  // 7: borrowers.BorrowersService.CreateBorrower:input_type -> borrowers.CreateBorrowerRequest
	2,  // 8: borrowers.BorrowersService.GetBorrowerById:input_type -> borrowers.GetBorrowerByIdRequest
	4,  // 9: borrowers.BorrowersService.UpdateBorrower:input_type -> borrowers.UpdateBorrowerRequest
	6,  // 10: borrowers.BorrowersService.DeleteBorrower:input_type -> borrowers.DeleteBorrowerRequest
	8,  // 11: borrowers.BorrowersService.GetAllBorrowers:input_type -> borrowers.GetAllBorrowersRequest
	11, // 12: borrowers.BorrowersService.GetBorrowingHistory:input_type -> borrowers.GetBorrowingHistoryRequest
	13, // 13: borrowers.BorrowersService.GetBorrowedBooksByUser:input_type -> borrowers.GetBorrowedBooksByUserRequest
	1,  // 14: borrowers.BorrowersService.CreateBorrower:output_type -> borrowers.CreateBorrowerResponse
	3,  // 15: borrowers.BorrowersService.GetBorrowerById:output_type -> borrowers.GetBorrowerByIdResponse
	5,  // 16: borrowers.BorrowersService.UpdateBorrower:output_type -> borrowers.UpdateBorrowerResponse
	7,  // 17: borrowers.BorrowersService.DeleteBorrower:output_type -> borrowers.DeleteBorrowerResponse
	10, // 18: borrowers.BorrowersService.GetAllBorrowers:output_type -> borrowers.GetAllBorrowersResponse
	12, // 19: borrowers.BorrowersService.GetBorrowingHistory:output_type -> borrowers.GetBorrowingHistoryResponse
	15, // 20: borrowers.BorrowersService.GetBorrowedBooksByUser:output_type -> borrowers.GetBorrowedBooksByUserResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protos_borrowers_proto_init() }
func file_protos_borrowers_proto_init() {
	if File_protos_borrowers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_borrowers_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBorrowerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBorrowerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetBorrowerByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetBorrowerByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateBorrowerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateBorrowerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBorrowerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBorrowerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllBorrowersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Borrower); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllBorrowersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetBorrowingHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetBorrowingHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetBorrowedBooksByUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*BorrowedBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrowers_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GetBorrowedBooksByUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_borrowers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_borrowers_proto_goTypes,
		DependencyIndexes: file_protos_borrowers_proto_depIdxs,
		MessageInfos:      file_protos_borrowers_proto_msgTypes,
	}.Build()
	File_protos_borrowers_proto = out.File
	file_protos_borrowers_proto_rawDesc = nil
	file_protos_borrowers_proto_goTypes = nil
	file_protos_borrowers_proto_depIdxs = nil
}
