// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: protos/gener.proto

package genres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AuthorId  string `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	GenreId   string `protobuf:"bytes,4,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	Summary   string `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAt string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt string `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Book) GetGenreId() string {
	if x != nil {
		return x.GenreId
	}
	return ""
}

func (x *Book) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Book) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Book) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Book) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type GetgenresByGenreIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetgenresByGenreIdRequest) Reset() {
	*x = GetgenresByGenreIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetgenresByGenreIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetgenresByGenreIdRequest) ProtoMessage() {}

func (x *GetgenresByGenreIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetgenresByGenreIdRequest.ProtoReflect.Descriptor instead.
func (*GetgenresByGenreIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{1}
}

func (x *GetgenresByGenreIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetgenresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books []*Book `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
}

func (x *GetgenresResponse) Reset() {
	*x = GetgenresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetgenresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetgenresResponse) ProtoMessage() {}

func (x *GetgenresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetgenresResponse.ProtoReflect.Descriptor instead.
func (*GetgenresResponse) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{2}
}

func (x *GetgenresResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

// Genre message represents the genre entity
type Genre struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt string `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *Genre) Reset() {
	*x = Genre{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{3}
}

func (x *Genre) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Genre) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Genre) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Genre) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

// Request and Response messages for getting genres
type GetGenresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetGenresRequest) Reset() {
	*x = GetGenresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenresRequest) ProtoMessage() {}

func (x *GetGenresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenresRequest.ProtoReflect.Descriptor instead.
func (*GetGenresRequest) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{4}
}

func (x *GetGenresRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetGenresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genres []*Genre `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
}

func (x *GetGenresResponse) Reset() {
	*x = GetGenresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenresResponse) ProtoMessage() {}

func (x *GetGenresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenresResponse.ProtoReflect.Descriptor instead.
func (*GetGenresResponse) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{5}
}

func (x *GetGenresResponse) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

// Request and Response messages for getting a genre by ID
type GetGenreByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGenreByIdRequest) Reset() {
	*x = GetGenreByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenreByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenreByIdRequest) ProtoMessage() {}

func (x *GetGenreByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenreByIdRequest.ProtoReflect.Descriptor instead.
func (*GetGenreByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{6}
}

func (x *GetGenreByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGenreByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genre *Genre `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
}

func (x *GetGenreByIdResponse) Reset() {
	*x = GetGenreByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenreByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenreByIdResponse) ProtoMessage() {}

func (x *GetGenreByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenreByIdResponse.ProtoReflect.Descriptor instead.
func (*GetGenreByIdResponse) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{7}
}

func (x *GetGenreByIdResponse) GetGenre() *Genre {
	if x != nil {
		return x.Genre
	}
	return nil
}

// Request and Response messages for creating a genre
type CreateGenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateGenreRequest) Reset() {
	*x = CreateGenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenreRequest) ProtoMessage() {}

func (x *CreateGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenreRequest.ProtoReflect.Descriptor instead.
func (*CreateGenreRequest) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{8}
}

func (x *CreateGenreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateGenreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genre *Genre `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
}

func (x *CreateGenreResponse) Reset() {
	*x = CreateGenreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGenreResponse) ProtoMessage() {}

func (x *CreateGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGenreResponse.ProtoReflect.Descriptor instead.
func (*CreateGenreResponse) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{9}
}

func (x *CreateGenreResponse) GetGenre() *Genre {
	if x != nil {
		return x.Genre
	}
	return nil
}

// Request and Response messages for updating a genre
type UpdateGenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateGenreRequest) Reset() {
	*x = UpdateGenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGenreRequest) ProtoMessage() {}

func (x *UpdateGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGenreRequest.ProtoReflect.Descriptor instead.
func (*UpdateGenreRequest) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateGenreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGenreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateGenreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genre *Genre `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
}

func (x *UpdateGenreResponse) Reset() {
	*x = UpdateGenreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGenreResponse) ProtoMessage() {}

func (x *UpdateGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGenreResponse.ProtoReflect.Descriptor instead.
func (*UpdateGenreResponse) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateGenreResponse) GetGenre() *Genre {
	if x != nil {
		return x.Genre
	}
	return nil
}

// Request and Response messages for deleting a genre
type DeleteGenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteGenreRequest) Reset() {
	*x = DeleteGenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenreRequest) ProtoMessage() {}

func (x *DeleteGenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGenreRequest.ProtoReflect.Descriptor instead.
func (*DeleteGenreRequest) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteGenreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGenreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteGenreResponse) Reset() {
	*x = DeleteGenreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gener_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGenreResponse) ProtoMessage() {}

func (x *DeleteGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gener_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGenreResponse.ProtoReflect.Descriptor instead.
func (*DeleteGenreResponse) Descriptor() ([]byte, []int) {
	return file_protos_gener_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteGenreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_gener_proto protoreflect.FileDescriptor

var file_protos_gener_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x22, 0xdb, 0x01, 0x0a,
	0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2b, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x42, 0x79, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05,
	0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73,
	0x22, 0x88, 0x01, 0x0a, 0x05, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x26, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x73, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x22,
	0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e,
	0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x05, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x6e,
	0x72, 0x65, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x22, 0x38, 0x0a, 0x12, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x22,
	0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xc7, 0x03, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x72, 0x65,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x72,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x2e, 0x67, 0x65, 0x6e,
	0x72, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x12, 0x1a, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a,
	0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x1a, 0x2e, 0x67,
	0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x12, 0x1a, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x42, 0x79, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x49, 0x64, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x12, 0x21, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x67,
	0x65, 0x6e, 0x72, 0x65, 0x73, 0x42, 0x79, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x12, 0x5a, 0x10, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_gener_proto_rawDescOnce sync.Once
	file_protos_gener_proto_rawDescData = file_protos_gener_proto_rawDesc
)

func file_protos_gener_proto_rawDescGZIP() []byte {
	file_protos_gener_proto_rawDescOnce.Do(func() {
		file_protos_gener_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_gener_proto_rawDescData)
	})
	return file_protos_gener_proto_rawDescData
}

var file_protos_gener_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_protos_gener_proto_goTypes = []any{
	(*Book)(nil),                      // 0: genres.Book
	(*GetgenresByGenreIdRequest)(nil), // 1: genres.GetgenresByGenreIdRequest
	(*GetgenresResponse)(nil),         // 2: genres.GetgenresResponse
	(*Genre)(nil),                     // 3: genres.Genre
	(*GetGenresRequest)(nil),          // 4: genres.GetGenresRequest
	(*GetGenresResponse)(nil),         // 5: genres.GetGenresResponse
	(*GetGenreByIdRequest)(nil),       // 6: genres.GetGenreByIdRequest
	(*GetGenreByIdResponse)(nil),      // 7: genres.GetGenreByIdResponse
	(*CreateGenreRequest)(nil),        // 8: genres.CreateGenreRequest
	(*CreateGenreResponse)(nil),       // 9: genres.CreateGenreResponse
	(*UpdateGenreRequest)(nil),        // 10: genres.UpdateGenreRequest
	(*UpdateGenreResponse)(nil),       // 11: genres.UpdateGenreResponse
	(*DeleteGenreRequest)(nil),        // 12: genres.DeleteGenreRequest
	(*DeleteGenreResponse)(nil),       // 13: genres.DeleteGenreResponse
}
var file_protos_gener_proto_depIdxs = []int32{
	0,  // 0: genres.GetgenresResponse.books:type_name -> genres.Book
	3,  // 1: genres.GetGenresResponse.genres:type_name -> genres.Genre
	3,  // 2: genres.GetGenreByIdResponse.genre:type_name -> genres.Genre
	3,  // 3: genres.CreateGenreResponse.genre:type_name -> genres.Genre
	3,  // 4: genres.UpdateGenreResponse.genre:type_name -> genres.Genre
	4,  // 5: genres.GenresService.GetGenres:input_type -> genres.GetGenresRequest
	6,  // 6: genres.GenresService.GetGenreById:input_type -> genres.GetGenreByIdRequest
	8,  // 7: genres.GenresService.CreateGenre:input_type -> genres.CreateGenreRequest
	10, // 8: genres.GenresService.UpdateGenre:input_type -> genres.UpdateGenreRequest
	12, // 9: genres.GenresService.DeleteGenre:input_type -> genres.DeleteGenreRequest
	1,  // 10: genres.GenresService.GetByGenreIdBooks:input_type -> genres.GetgenresByGenreIdRequest
	5,  // 11: genres.GenresService.GetGenres:output_type -> genres.GetGenresResponse
	7,  // 12: genres.GenresService.GetGenreById:output_type -> genres.GetGenreByIdResponse
	9,  // 13: genres.GenresService.CreateGenre:output_type -> genres.CreateGenreResponse
	11, // 14: genres.GenresService.UpdateGenre:output_type -> genres.UpdateGenreResponse
	13, // 15: genres.GenresService.DeleteGenre:output_type -> genres.DeleteGenreResponse
	2,  // 16: genres.GenresService.GetByGenreIdBooks:output_type -> genres.GetgenresResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protos_gener_proto_init() }
func file_protos_gener_proto_init() {
	if File_protos_gener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_gener_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetgenresByGenreIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetgenresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Genre); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetGenresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetGenresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetGenreByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetGenreByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGenreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGenreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteGenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gener_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteGenreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_gener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_gener_proto_goTypes,
		DependencyIndexes: file_protos_gener_proto_depIdxs,
		MessageInfos:      file_protos_gener_proto_msgTypes,
	}.Build()
	File_protos_gener_proto = out.File
	file_protos_gener_proto_rawDesc = nil
	file_protos_gener_proto_goTypes = nil
	file_protos_gener_proto_depIdxs = nil
}
