name: Library service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout our repository
      uses: actions/checkout@v4

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd web-poll
          git pull origin main
          echo ---------------- PULLED CODE ----------------

          cd Library
          echo ---------------- DIR CHANGED TO Library ----------------
          sudo docker compose down
          echo ---------------- DOWN Library ----------------
          sudo docker compose up -d
          echo ---------------- UP Library ----------------

          cd ../api-gateway
          echo ---------------- DIR CHANGED TO API-GATEWAY ----------------
          sudo docker compose down
          echo ---------------- DOWN API-GATEWAY ----------------
          sudo docker compose up -d
          echo ---------------- UP API-GATEWAY ----------------

          cd ../api-gateway-user
          echo ---------------- DIR CHANGED TO API-GATEWAY-USER ----------------
          sudo docker compose down
          echo ---------------- DOWN API-GATEWAY-USER ----------------
          sudo docker compose up -d
          echo ---------------- UP API-GATEWAY-USER ----------------